name: Z3-Noodler Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          wait-for-completion: true

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          generate_release_notes: true  # optional
