name: Z3-Noodler Test

on:
  push:

permissions:
  contents: read

jobs:
  call_build:
    uses: ./.github/workflows/noodler-build.yml

  test:
    name: Test (${{ matrix.os }} / ${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    needs: call_build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu
            arch: x86_64
            runner: ubuntu-latest
          - os: macos
            arch: x86_64
            runner: macos-15-intel
          - os: macos
            arch: arm64
            runner: macos-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: z3-noodler-${{ matrix.os }}-${{ matrix.arch }}
          path: build

      - name: Run tests
        run: |
          cd build/
          ./z3-noodler-${{ matrix.os }}-${{ matrix.arch }}
